version: "3.7"
services:
    nginx:
        image: nginx:alpine
        container_name: morgage-calculator-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html:cached
            - ./.docker/nginx:/etc/nginx/conf.d
        networks:
            - morgage-calculator-network
        depends_on:
            - app

    app:
        build:
            args:
                user: summiya
                uid: 1000
            context: ./.docker/app
            dockerfile: Dockerfile
        image: morgage-calculator
        container_name: morgage-calculator
        restart: unless-stopped
        ports:
            - 6001:6001
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:cached
            - ./.docker/app/php-fpm.ini:/usr/local/etc/php/conf.d/99-app.ini
        networks:
            - morgage-calculator-network
        depends_on:
            - database

    database:
        image: mariadb:10.5.8
        container_name: morgage-calculator-mariadb
        restart: unless-stopped
        ports:
            - 3304:3304
        volumes:
            - morgage-calculator-volume:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        networks:
            - morgage-calculator-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: morgage-calculator-phpmyadmin
        restart: unless-stopped
        tty: true
        depends_on:
            - database
        ports:
            - 8088:80
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 300M
        networks:
            - morgage-calculator-network
networks:
    morgage-calculator-network:
        driver: bridge

volumes:
    morgage-calculator-volume:
        driver: local
